export const cart = [
  {
    id: '1',
    product: {
      id: "10",
      name: "ssd",
      description: "val",
      netPrice: 95,
      weight: 100,
      discount: 5,
    },
    quantity: 2,
  },
  {
    id: '2',
    product: {
      id: "11",
      name: "motherboard",
      description: "val",
      netPrice: 270,
      weight: 900,
      discount: 0,
    },
    quantity: 1,
  },
  {
    id: '3',
    product: {
      id: "12",
      name: "ram",
      description: "val",
      netPrice: 120,
      weight: 60,
      discount: 10,
    },
    quantity: 2,
  },
  {
    id: '4',
    product: {
      id: "13",
      name: "processor",
      description: "val",
      netPrice: 400,
      weight: 130,
      discount: 0,
    },
    quantity: 1,
  },
  {
    id: '5',
    product: {
      id: "14",
      name: "power supply",
      description: "val",
      netPrice: 130,
      weight: 1400,
      discount: 15,
    },
    quantity: 1,
  },
  {
    id: '6',
    product: {
      id: "15",
      name: "cpu cooler",
      description: "val",
      netPrice: 170,
      weight: 1000,
      discount: 23,
    },
    quantity: 1,
  },
  {
    id: '7',
    product: {
      id: "16",
      name: "gpu",
      description: "val",
      netPrice: 1600,
      weight: 2500,
      discount: 0,
    },
    quantity: 1,
  },
  {
    id: '8',
    product: {
      id: "17",
      name: "case",
      description: "val",
      netPrice: 130,
      weight: 3500,
      discount: 30,
    },
    quantity: 1,
  },
];
